name: automatic eas build
on:
  push:
      branches:
        - main
        - development
        - scanner-checking-ingredients
  workflow_dispatch:

jobs:
  automated-build:
      runs-on: ubuntu-latest
      steps:
        - name: Check for EXPO_TOKEN
          run: |
            if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
              echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
              exit 1
            fi

        - uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: npm
            cache-dependency-path: frontend/package-lock.json

        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '17'
            cache: 'gradle'

        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
        
        - name: install dependencies
          working-directory: ./frontend
          run: npm install

        - name: setting permissions
          working-directory: ./frontend
          run: chmod +x eas-hooks/*.sh
            
        - name: build android locally 
          working-directory: ./frontend
          run: eas build -p android -e test --local

