name: iOS App Release Build

on:
  push:
      branches:
        - main
        - scanner-checking-ingredients
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build iOS app
        working-directory: ./frontend
        run: eas build --platform ios --local --non-interactive --output ../${{ github.workspace }}/app-release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.ipa