name: Android App Release Build

on:
  push:
      branches:
        - main
        - scanner-checking-ingredients
  workflow_dispatch:

jobs:
  automated-build-android:
      runs-on: ubuntu-latest
      steps:
        - name: Setup repo
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: npm
            cache-dependency-path: frontend/package-lock.json

        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '17'
        
        - name: Setup Android SDK
          uses: android-actions/setup-android@v3

        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
        
        - name: install dependencies
          working-directory: ./frontend
          run: npm ci

        - name: setting permissions
          working-directory: ./frontend
          run: chmod +x eas-hooks/*.sh
            
        - name: build android locally 
          working-directory: ./frontend
          run: eas build --platform android --profile preview --local --output ../${{ github.workspace }}/app-release.apk

        - name: Upload APK artifact
          uses: actions/upload-artifact@v2
          with:
            name: app-release
            path: ${{ github.workspace }}/app-release.apk

