name: App Release Build

on:
  push:
    branches:
      - main
      - scanner-checking-ingredients
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: default
          channel: stable

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Setting permissions
        working-directory: ./frontend
        run: chmod +x eas-hooks/*.sh

      - name: Build android locally
        working-directory: ./frontend
        run: eas build --platform android --profile preview --local --output ${{ github.workspace }}/app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.apk

      - name: Set up emulator
        run: |
          sudo $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;google_apis;x86_64"
          echo "y" | sudo $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
          $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -accel on &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Run Detox tests
        working-directory: ./frontend
        run: |
          npm run detox:build:android
          npm run detox:test:android

  # Doesn't work because paid apple developer license needed
  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Setup repo
  #       uses: actions/checkout@v4

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.x
  #         cache: npm
  #         cache-dependency-path: frontend/package-lock.json

  #     - name: Setup EAS
  #       uses: expo/expo-github-action@v8
  #       with:
  #         eas-version: latest
  #         token: ${{ secrets.EXPO_TOKEN }}

  #     - name: Install dependencies
  #       working-directory: ./frontend
  #       run: npm ci

  #     - name: Build iOS app
  #       working-directory: ./frontend
  #       run: eas build --platform ios --local --non-interactive --profile production --output ${{ github.workspace }}/app-release-ios.ipa

  #     - name: Upload IPA artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: app-release-ios
  #         path: ${{ github.workspace }}/app-release-ios.ipa
