name: Automated API tests using Postman CLI
on:
  push:
      branches:
        - main
        - development
        - setup-github-actions
  workflow_dispatch:

jobs:
  automated-api-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install Postman CLI
          run: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

        - name: Login to Postman CLI
          run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

        - name: Run API tests
          run: |
            postman collection run 5663493-8a28fab3-3465-4f69-b9fd-cbca6bff5a89
            postman collection run 5663493-7dccfde7-0a82-4825-9e29-6bec947884c5  
            

