name: Automated API integration tests using Postman CLI
on:
  push:
      branches:
        - main
        - development
        - setup-github-actions
  workflow_dispatch:

jobs:
  automated-integration-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install Postman CLI
          run: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

        - name: Login to Postman CLI
          run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

        - name: Run integration tests Azure Vision API
          run: postman collection run 5663493-a5fd178c-f7a8-4401-af14-e017c47ede2f

        - name: Run integration tests OpenFoodFacts API
          run: postman collection run 5663493-ae347f91-39df-42e1-9596-0cd07d03eaa6
            

